IMAGE_SIZE_WIDTH = 92
IMAGE_SIZE_HEIGHT = 112

K_CROSS_VALIDATION = 5

DEFAULT_NO_OF_FILES = 10
DEFAULT_FLATTENED_SIZE = 10304
DEFAULT_NO_OF_CLASSES = 40
FACE_FOLDER_NAME = "faces"

NO_OF_PCA_COMPONENTS = 20

LABEL_C1 = 1
LABEL_C2 = -1